version: '2'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./live/redis-data/:/data

  sentry_redis:
    image: redis

  lb:
    build: ./nginx
    ports:
     - "8080:80"
    depends_on:
     - app

  postgres:
    image: postgres
    volumes:
     - postgres-db-volume:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentry

  sentry:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    links:
     - sentry_redis
     - postgres
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis

  sentry_worker:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis
      C_FORCE_ROOT: 1

  sentry_cron:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis
      C_FORCE_ROOT: 1

  app:
    build: ./app
    depends_on:
      - redis
      
volumes:
  postgres-db-volume:
      
