// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appstate.proto

package club.eslcc.bigsciencequiz.proto;

public final class Appstate {
  private Appstate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.AppState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    boolean hasGameState();
    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Gamestate.GameState getGameState();
    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getGameStateOrBuilder();

    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    boolean hasTeam();
    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.User.Team getTeam();
    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamOrBuilder();

    /**
     * <code>int32 userAnswer = 3;</code>
     */
    int getUserAnswer();

    /**
     * <code>int32 correctAnswer = 4;</code>
     */
    int getCorrectAnswer();
  }
  /**
   * Protobuf type {@code bigsciencequiz.AppState}
   */
  public  static final class AppState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.AppState)
      AppStateOrBuilder {
    // Use AppState.newBuilder() to construct.
    private AppState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppState() {
      userAnswer_ = 0;
      correctAnswer_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder subBuilder = null;
              if (gameState_ != null) {
                subBuilder = gameState_.toBuilder();
              }
              gameState_ = input.readMessage(club.eslcc.bigsciencequiz.proto.Gamestate.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(gameState_);
                gameState_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              club.eslcc.bigsciencequiz.proto.User.Team.Builder subBuilder = null;
              if (team_ != null) {
                subBuilder = team_.toBuilder();
              }
              team_ = input.readMessage(club.eslcc.bigsciencequiz.proto.User.Team.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(team_);
                team_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              userAnswer_ = input.readInt32();
              break;
            }
            case 32: {

              correctAnswer_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.Appstate.internal_static_bigsciencequiz_AppState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.Appstate.internal_static_bigsciencequiz_AppState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.Appstate.AppState.class, club.eslcc.bigsciencequiz.proto.Appstate.AppState.Builder.class);
    }

    public static final int GAMESTATE_FIELD_NUMBER = 1;
    private club.eslcc.bigsciencequiz.proto.Gamestate.GameState gameState_;
    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    public boolean hasGameState() {
      return gameState_ != null;
    }
    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getGameState() {
      return gameState_ == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : gameState_;
    }
    /**
     * <code>.bigsciencequiz.GameState gameState = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getGameStateOrBuilder() {
      return getGameState();
    }

    public static final int TEAM_FIELD_NUMBER = 2;
    private club.eslcc.bigsciencequiz.proto.User.Team team_;
    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    public boolean hasTeam() {
      return team_ != null;
    }
    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.User.Team getTeam() {
      return team_ == null ? club.eslcc.bigsciencequiz.proto.User.Team.getDefaultInstance() : team_;
    }
    /**
     * <code>.bigsciencequiz.Team team = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamOrBuilder() {
      return getTeam();
    }

    public static final int USERANSWER_FIELD_NUMBER = 3;
    private int userAnswer_;
    /**
     * <code>int32 userAnswer = 3;</code>
     */
    public int getUserAnswer() {
      return userAnswer_;
    }

    public static final int CORRECTANSWER_FIELD_NUMBER = 4;
    private int correctAnswer_;
    /**
     * <code>int32 correctAnswer = 4;</code>
     */
    public int getCorrectAnswer() {
      return correctAnswer_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (gameState_ != null) {
        output.writeMessage(1, getGameState());
      }
      if (team_ != null) {
        output.writeMessage(2, getTeam());
      }
      if (userAnswer_ != 0) {
        output.writeInt32(3, userAnswer_);
      }
      if (correctAnswer_ != 0) {
        output.writeInt32(4, correctAnswer_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (gameState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameState());
      }
      if (team_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTeam());
      }
      if (userAnswer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userAnswer_);
      }
      if (correctAnswer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, correctAnswer_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.Appstate.AppState)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.Appstate.AppState other = (club.eslcc.bigsciencequiz.proto.Appstate.AppState) obj;

      boolean result = true;
      result = result && (hasGameState() == other.hasGameState());
      if (hasGameState()) {
        result = result && getGameState()
            .equals(other.getGameState());
      }
      result = result && (hasTeam() == other.hasTeam());
      if (hasTeam()) {
        result = result && getTeam()
            .equals(other.getTeam());
      }
      result = result && (getUserAnswer()
          == other.getUserAnswer());
      result = result && (getCorrectAnswer()
          == other.getCorrectAnswer());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGameState()) {
        hash = (37 * hash) + GAMESTATE_FIELD_NUMBER;
        hash = (53 * hash) + getGameState().hashCode();
      }
      if (hasTeam()) {
        hash = (37 * hash) + TEAM_FIELD_NUMBER;
        hash = (53 * hash) + getTeam().hashCode();
      }
      hash = (37 * hash) + USERANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getUserAnswer();
      hash = (37 * hash) + CORRECTANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getCorrectAnswer();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.Appstate.AppState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.AppState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.AppState)
        club.eslcc.bigsciencequiz.proto.Appstate.AppStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Appstate.internal_static_bigsciencequiz_AppState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.Appstate.internal_static_bigsciencequiz_AppState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.Appstate.AppState.class, club.eslcc.bigsciencequiz.proto.Appstate.AppState.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.Appstate.AppState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (gameStateBuilder_ == null) {
          gameState_ = null;
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }
        if (teamBuilder_ == null) {
          team_ = null;
        } else {
          team_ = null;
          teamBuilder_ = null;
        }
        userAnswer_ = 0;

        correctAnswer_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.Appstate.internal_static_bigsciencequiz_AppState_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.Appstate.AppState getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.Appstate.AppState.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.Appstate.AppState build() {
        club.eslcc.bigsciencequiz.proto.Appstate.AppState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.Appstate.AppState buildPartial() {
        club.eslcc.bigsciencequiz.proto.Appstate.AppState result = new club.eslcc.bigsciencequiz.proto.Appstate.AppState(this);
        if (gameStateBuilder_ == null) {
          result.gameState_ = gameState_;
        } else {
          result.gameState_ = gameStateBuilder_.build();
        }
        if (teamBuilder_ == null) {
          result.team_ = team_;
        } else {
          result.team_ = teamBuilder_.build();
        }
        result.userAnswer_ = userAnswer_;
        result.correctAnswer_ = correctAnswer_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.Appstate.AppState) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.Appstate.AppState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.Appstate.AppState other) {
        if (other == club.eslcc.bigsciencequiz.proto.Appstate.AppState.getDefaultInstance()) return this;
        if (other.hasGameState()) {
          mergeGameState(other.getGameState());
        }
        if (other.hasTeam()) {
          mergeTeam(other.getTeam());
        }
        if (other.getUserAnswer() != 0) {
          setUserAnswer(other.getUserAnswer());
        }
        if (other.getCorrectAnswer() != 0) {
          setCorrectAnswer(other.getCorrectAnswer());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.Appstate.AppState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.Appstate.AppState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private club.eslcc.bigsciencequiz.proto.Gamestate.GameState gameState_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder> gameStateBuilder_;
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public boolean hasGameState() {
        return gameStateBuilder_ != null || gameState_ != null;
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getGameState() {
        if (gameStateBuilder_ == null) {
          return gameState_ == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : gameState_;
        } else {
          return gameStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public Builder setGameState(club.eslcc.bigsciencequiz.proto.Gamestate.GameState value) {
        if (gameStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gameState_ = value;
          onChanged();
        } else {
          gameStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public Builder setGameState(
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder builderForValue) {
        if (gameStateBuilder_ == null) {
          gameState_ = builderForValue.build();
          onChanged();
        } else {
          gameStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public Builder mergeGameState(club.eslcc.bigsciencequiz.proto.Gamestate.GameState value) {
        if (gameStateBuilder_ == null) {
          if (gameState_ != null) {
            gameState_ =
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.newBuilder(gameState_).mergeFrom(value).buildPartial();
          } else {
            gameState_ = value;
          }
          onChanged();
        } else {
          gameStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public Builder clearGameState() {
        if (gameStateBuilder_ == null) {
          gameState_ = null;
          onChanged();
        } else {
          gameState_ = null;
          gameStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder getGameStateBuilder() {
        
        onChanged();
        return getGameStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getGameStateOrBuilder() {
        if (gameStateBuilder_ != null) {
          return gameStateBuilder_.getMessageOrBuilder();
        } else {
          return gameState_ == null ?
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : gameState_;
        }
      }
      /**
       * <code>.bigsciencequiz.GameState gameState = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder> 
          getGameStateFieldBuilder() {
        if (gameStateBuilder_ == null) {
          gameStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder>(
                  getGameState(),
                  getParentForChildren(),
                  isClean());
          gameState_ = null;
        }
        return gameStateBuilder_;
      }

      private club.eslcc.bigsciencequiz.proto.User.Team team_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> teamBuilder_;
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public boolean hasTeam() {
        return teamBuilder_ != null || team_ != null;
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team getTeam() {
        if (teamBuilder_ == null) {
          return team_ == null ? club.eslcc.bigsciencequiz.proto.User.Team.getDefaultInstance() : team_;
        } else {
          return teamBuilder_.getMessage();
        }
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public Builder setTeam(club.eslcc.bigsciencequiz.proto.User.Team value) {
        if (teamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          team_ = value;
          onChanged();
        } else {
          teamBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public Builder setTeam(
          club.eslcc.bigsciencequiz.proto.User.Team.Builder builderForValue) {
        if (teamBuilder_ == null) {
          team_ = builderForValue.build();
          onChanged();
        } else {
          teamBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public Builder mergeTeam(club.eslcc.bigsciencequiz.proto.User.Team value) {
        if (teamBuilder_ == null) {
          if (team_ != null) {
            team_ =
              club.eslcc.bigsciencequiz.proto.User.Team.newBuilder(team_).mergeFrom(value).buildPartial();
          } else {
            team_ = value;
          }
          onChanged();
        } else {
          teamBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public Builder clearTeam() {
        if (teamBuilder_ == null) {
          team_ = null;
          onChanged();
        } else {
          team_ = null;
          teamBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team.Builder getTeamBuilder() {
        
        onChanged();
        return getTeamFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamOrBuilder() {
        if (teamBuilder_ != null) {
          return teamBuilder_.getMessageOrBuilder();
        } else {
          return team_ == null ?
              club.eslcc.bigsciencequiz.proto.User.Team.getDefaultInstance() : team_;
        }
      }
      /**
       * <code>.bigsciencequiz.Team team = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> 
          getTeamFieldBuilder() {
        if (teamBuilder_ == null) {
          teamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder>(
                  getTeam(),
                  getParentForChildren(),
                  isClean());
          team_ = null;
        }
        return teamBuilder_;
      }

      private int userAnswer_ ;
      /**
       * <code>int32 userAnswer = 3;</code>
       */
      public int getUserAnswer() {
        return userAnswer_;
      }
      /**
       * <code>int32 userAnswer = 3;</code>
       */
      public Builder setUserAnswer(int value) {
        
        userAnswer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userAnswer = 3;</code>
       */
      public Builder clearUserAnswer() {
        
        userAnswer_ = 0;
        onChanged();
        return this;
      }

      private int correctAnswer_ ;
      /**
       * <code>int32 correctAnswer = 4;</code>
       */
      public int getCorrectAnswer() {
        return correctAnswer_;
      }
      /**
       * <code>int32 correctAnswer = 4;</code>
       */
      public Builder setCorrectAnswer(int value) {
        
        correctAnswer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 correctAnswer = 4;</code>
       */
      public Builder clearCorrectAnswer() {
        
        correctAnswer_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.AppState)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.AppState)
    private static final club.eslcc.bigsciencequiz.proto.Appstate.AppState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.Appstate.AppState();
    }

    public static club.eslcc.bigsciencequiz.proto.Appstate.AppState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppState>
        PARSER = new com.google.protobuf.AbstractParser<AppState>() {
      public AppState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppState> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.Appstate.AppState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_AppState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_AppState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016appstate.proto\022\016bigsciencequiz\032\017gamest" +
      "ate.proto\032\nuser.proto\"\207\001\n\010AppState\022,\n\tga" +
      "meState\030\001 \001(\0132\031.bigsciencequiz.GameState" +
      "\022\"\n\004team\030\002 \001(\0132\024.bigsciencequiz.Team\022\022\n\n" +
      "userAnswer\030\003 \001(\005\022\025\n\rcorrectAnswer\030\004 \001(\005B" +
      "!\n\037club.eslcc.bigsciencequiz.protob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          club.eslcc.bigsciencequiz.proto.Gamestate.getDescriptor(),
          club.eslcc.bigsciencequiz.proto.User.getDescriptor(),
        }, assigner);
    internal_static_bigsciencequiz_AppState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bigsciencequiz_AppState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_AppState_descriptor,
        new java.lang.String[] { "GameState", "Team", "UserAnswer", "CorrectAnswer", });
    club.eslcc.bigsciencequiz.proto.Gamestate.getDescriptor();
    club.eslcc.bigsciencequiz.proto.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
