// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gamestate.proto

package club.eslcc.bigsciencequiz.proto;

public final class Gamestate {
  private Gamestate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.GameState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.bigsciencequiz.GameState.State state = 1;</code>
     */
    int getStateValue();
    /**
     * <code>.bigsciencequiz.GameState.State state = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State getState();

    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    boolean hasCurrentQuestion();
    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question getCurrentQuestion();
    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder getCurrentQuestionOrBuilder();

    /**
     * <code>bool currentQuestionAnswered = 3;</code>
     */
    boolean getCurrentQuestionAnswered();
  }
  /**
   * Protobuf type {@code bigsciencequiz.GameState}
   */
  public  static final class GameState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.GameState)
      GameStateOrBuilder {
    // Use GameState.newBuilder() to construct.
    private GameState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameState() {
      state_ = 0;
      currentQuestionAnswered_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GameState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            case 18: {
              club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder subBuilder = null;
              if (currentQuestion_ != null) {
                subBuilder = currentQuestion_.toBuilder();
              }
              currentQuestion_ = input.readMessage(club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(currentQuestion_);
                currentQuestion_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              currentQuestionAnswered_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.Gamestate.internal_static_bigsciencequiz_GameState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.Gamestate.internal_static_bigsciencequiz_GameState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.class, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder.class);
    }

    /**
     * Protobuf enum {@code bigsciencequiz.GameState.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NOTREADY = 0;</code>
       */
      NOTREADY(0),
      /**
       * <code>INTRO = 1;</code>
       */
      INTRO(1),
      /**
       * <code>READY = 2;</code>
       */
      READY(2),
      /**
       * <code>STARTING = 3;</code>
       */
      STARTING(3),
      /**
       * <code>QUESTION_ANSWERING = 4;</code>
       */
      QUESTION_ANSWERING(4),
      /**
       * <code>QUESTION_LIVEANSWERS = 5;</code>
       */
      QUESTION_LIVEANSWERS(5),
      /**
       * <code>QUESTION_CLOSED = 6;</code>
       */
      QUESTION_CLOSED(6),
      /**
       * <code>QUESTION_ANSWERS_REVEALED = 7;</code>
       */
      QUESTION_ANSWERS_REVEALED(7),
      /**
       * <code>LEADERBOARD = 8;</code>
       */
      LEADERBOARD(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NOTREADY = 0;</code>
       */
      public static final int NOTREADY_VALUE = 0;
      /**
       * <code>INTRO = 1;</code>
       */
      public static final int INTRO_VALUE = 1;
      /**
       * <code>READY = 2;</code>
       */
      public static final int READY_VALUE = 2;
      /**
       * <code>STARTING = 3;</code>
       */
      public static final int STARTING_VALUE = 3;
      /**
       * <code>QUESTION_ANSWERING = 4;</code>
       */
      public static final int QUESTION_ANSWERING_VALUE = 4;
      /**
       * <code>QUESTION_LIVEANSWERS = 5;</code>
       */
      public static final int QUESTION_LIVEANSWERS_VALUE = 5;
      /**
       * <code>QUESTION_CLOSED = 6;</code>
       */
      public static final int QUESTION_CLOSED_VALUE = 6;
      /**
       * <code>QUESTION_ANSWERS_REVEALED = 7;</code>
       */
      public static final int QUESTION_ANSWERS_REVEALED_VALUE = 7;
      /**
       * <code>LEADERBOARD = 8;</code>
       */
      public static final int LEADERBOARD_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      public static State forNumber(int value) {
        switch (value) {
          case 0: return NOTREADY;
          case 1: return INTRO;
          case 2: return READY;
          case 3: return STARTING;
          case 4: return QUESTION_ANSWERING;
          case 5: return QUESTION_LIVEANSWERS;
          case 6: return QUESTION_CLOSED;
          case 7: return QUESTION_ANSWERS_REVEALED;
          case 8: return LEADERBOARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:bigsciencequiz.GameState.State)
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>.bigsciencequiz.GameState.State state = 1;</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <code>.bigsciencequiz.GameState.State state = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State getState() {
      club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State result = club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.valueOf(state_);
      return result == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.UNRECOGNIZED : result;
    }

    public static final int CURRENTQUESTION_FIELD_NUMBER = 2;
    private club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question currentQuestion_;
    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    public boolean hasCurrentQuestion() {
      return currentQuestion_ != null;
    }
    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question getCurrentQuestion() {
      return currentQuestion_ == null ? club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.getDefaultInstance() : currentQuestion_;
    }
    /**
     * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder getCurrentQuestionOrBuilder() {
      return getCurrentQuestion();
    }

    public static final int CURRENTQUESTIONANSWERED_FIELD_NUMBER = 3;
    private boolean currentQuestionAnswered_;
    /**
     * <code>bool currentQuestionAnswered = 3;</code>
     */
    public boolean getCurrentQuestionAnswered() {
      return currentQuestionAnswered_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.NOTREADY.getNumber()) {
        output.writeEnum(1, state_);
      }
      if (currentQuestion_ != null) {
        output.writeMessage(2, getCurrentQuestion());
      }
      if (currentQuestionAnswered_ != false) {
        output.writeBool(3, currentQuestionAnswered_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.NOTREADY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (currentQuestion_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurrentQuestion());
      }
      if (currentQuestionAnswered_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, currentQuestionAnswered_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.Gamestate.GameState)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.Gamestate.GameState other = (club.eslcc.bigsciencequiz.proto.Gamestate.GameState) obj;

      boolean result = true;
      result = result && state_ == other.state_;
      result = result && (hasCurrentQuestion() == other.hasCurrentQuestion());
      if (hasCurrentQuestion()) {
        result = result && getCurrentQuestion()
            .equals(other.getCurrentQuestion());
      }
      result = result && (getCurrentQuestionAnswered()
          == other.getCurrentQuestionAnswered());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      if (hasCurrentQuestion()) {
        hash = (37 * hash) + CURRENTQUESTION_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentQuestion().hashCode();
      }
      hash = (37 * hash) + CURRENTQUESTIONANSWERED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCurrentQuestionAnswered());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.Gamestate.GameState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.GameState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.GameState)
        club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Gamestate.internal_static_bigsciencequiz_GameState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.Gamestate.internal_static_bigsciencequiz_GameState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.Gamestate.GameState.class, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.Gamestate.GameState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        state_ = 0;

        if (currentQuestionBuilder_ == null) {
          currentQuestion_ = null;
        } else {
          currentQuestion_ = null;
          currentQuestionBuilder_ = null;
        }
        currentQuestionAnswered_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.Gamestate.internal_static_bigsciencequiz_GameState_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState build() {
        club.eslcc.bigsciencequiz.proto.Gamestate.GameState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState buildPartial() {
        club.eslcc.bigsciencequiz.proto.Gamestate.GameState result = new club.eslcc.bigsciencequiz.proto.Gamestate.GameState(this);
        result.state_ = state_;
        if (currentQuestionBuilder_ == null) {
          result.currentQuestion_ = currentQuestion_;
        } else {
          result.currentQuestion_ = currentQuestionBuilder_.build();
        }
        result.currentQuestionAnswered_ = currentQuestionAnswered_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.Gamestate.GameState) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.Gamestate.GameState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.Gamestate.GameState other) {
        if (other == club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        if (other.hasCurrentQuestion()) {
          mergeCurrentQuestion(other.getCurrentQuestion());
        }
        if (other.getCurrentQuestionAnswered() != false) {
          setCurrentQuestionAnswered(other.getCurrentQuestionAnswered());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.Gamestate.GameState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.Gamestate.GameState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <code>.bigsciencequiz.GameState.State state = 1;</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <code>.bigsciencequiz.GameState.State state = 1;</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState.State state = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State getState() {
        club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State result = club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.valueOf(state_);
        return result == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State.UNRECOGNIZED : result;
      }
      /**
       * <code>.bigsciencequiz.GameState.State state = 1;</code>
       */
      public Builder setState(club.eslcc.bigsciencequiz.proto.Gamestate.GameState.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState.State state = 1;</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }

      private club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question currentQuestion_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder> currentQuestionBuilder_;
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public boolean hasCurrentQuestion() {
        return currentQuestionBuilder_ != null || currentQuestion_ != null;
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question getCurrentQuestion() {
        if (currentQuestionBuilder_ == null) {
          return currentQuestion_ == null ? club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.getDefaultInstance() : currentQuestion_;
        } else {
          return currentQuestionBuilder_.getMessage();
        }
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public Builder setCurrentQuestion(club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question value) {
        if (currentQuestionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          currentQuestion_ = value;
          onChanged();
        } else {
          currentQuestionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public Builder setCurrentQuestion(
          club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder builderForValue) {
        if (currentQuestionBuilder_ == null) {
          currentQuestion_ = builderForValue.build();
          onChanged();
        } else {
          currentQuestionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public Builder mergeCurrentQuestion(club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question value) {
        if (currentQuestionBuilder_ == null) {
          if (currentQuestion_ != null) {
            currentQuestion_ =
              club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.newBuilder(currentQuestion_).mergeFrom(value).buildPartial();
          } else {
            currentQuestion_ = value;
          }
          onChanged();
        } else {
          currentQuestionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public Builder clearCurrentQuestion() {
        if (currentQuestionBuilder_ == null) {
          currentQuestion_ = null;
          onChanged();
        } else {
          currentQuestion_ = null;
          currentQuestionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder getCurrentQuestionBuilder() {
        
        onChanged();
        return getCurrentQuestionFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder getCurrentQuestionOrBuilder() {
        if (currentQuestionBuilder_ != null) {
          return currentQuestionBuilder_.getMessageOrBuilder();
        } else {
          return currentQuestion_ == null ?
              club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.getDefaultInstance() : currentQuestion_;
        }
      }
      /**
       * <code>.bigsciencequiz.Question currentQuestion = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder> 
          getCurrentQuestionFieldBuilder() {
        if (currentQuestionBuilder_ == null) {
          currentQuestionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.Question.Builder, club.eslcc.bigsciencequiz.proto.QuestionOuterClass.QuestionOrBuilder>(
                  getCurrentQuestion(),
                  getParentForChildren(),
                  isClean());
          currentQuestion_ = null;
        }
        return currentQuestionBuilder_;
      }

      private boolean currentQuestionAnswered_ ;
      /**
       * <code>bool currentQuestionAnswered = 3;</code>
       */
      public boolean getCurrentQuestionAnswered() {
        return currentQuestionAnswered_;
      }
      /**
       * <code>bool currentQuestionAnswered = 3;</code>
       */
      public Builder setCurrentQuestionAnswered(boolean value) {
        
        currentQuestionAnswered_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool currentQuestionAnswered = 3;</code>
       */
      public Builder clearCurrentQuestionAnswered() {
        
        currentQuestionAnswered_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.GameState)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.GameState)
    private static final club.eslcc.bigsciencequiz.proto.Gamestate.GameState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.Gamestate.GameState();
    }

    public static club.eslcc.bigsciencequiz.proto.Gamestate.GameState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameState>
        PARSER = new com.google.protobuf.AbstractParser<GameState>() {
      public GameState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GameState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameState> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_GameState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_GameState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017gamestate.proto\022\016bigsciencequiz\032\016quest" +
      "ion.proto\"\302\002\n\tGameState\022.\n\005state\030\001 \001(\0162\037" +
      ".bigsciencequiz.GameState.State\0221\n\017curre" +
      "ntQuestion\030\002 \001(\0132\030.bigsciencequiz.Questi" +
      "on\022\037\n\027currentQuestionAnswered\030\003 \001(\010\"\260\001\n\005" +
      "State\022\014\n\010NOTREADY\020\000\022\t\n\005INTRO\020\001\022\t\n\005READY\020" +
      "\002\022\014\n\010STARTING\020\003\022\026\n\022QUESTION_ANSWERING\020\004\022" +
      "\030\n\024QUESTION_LIVEANSWERS\020\005\022\023\n\017QUESTION_CL" +
      "OSED\020\006\022\035\n\031QUESTION_ANSWERS_REVEALED\020\007\022\017\n" +
      "\013LEADERBOARD\020\010B!\n\037club.eslcc.bigscienceq",
      "uiz.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          club.eslcc.bigsciencequiz.proto.QuestionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_bigsciencequiz_GameState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bigsciencequiz_GameState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_GameState_descriptor,
        new java.lang.String[] { "State", "CurrentQuestion", "CurrentQuestionAnswered", });
    club.eslcc.bigsciencequiz.proto.QuestionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
