// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: events.proto

package club.eslcc.bigsciencequiz.proto;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GameStateChangeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.GameStateChangeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    boolean hasNewState();
    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Gamestate.GameState getNewState();
    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getNewStateOrBuilder();
  }
  /**
   * Protobuf type {@code bigsciencequiz.GameStateChangeEvent}
   */
  public  static final class GameStateChangeEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.GameStateChangeEvent)
      GameStateChangeEventOrBuilder {
    // Use GameStateChangeEvent.newBuilder() to construct.
    private GameStateChangeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameStateChangeEvent() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GameStateChangeEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder subBuilder = null;
              if (newState_ != null) {
                subBuilder = newState_.toBuilder();
              }
              newState_ = input.readMessage(club.eslcc.bigsciencequiz.proto.Gamestate.GameState.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(newState_);
                newState_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameStateChangeEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameStateChangeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.class, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder.class);
    }

    public static final int NEWSTATE_FIELD_NUMBER = 1;
    private club.eslcc.bigsciencequiz.proto.Gamestate.GameState newState_;
    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    public boolean hasNewState() {
      return newState_ != null;
    }
    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getNewState() {
      return newState_ == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : newState_;
    }
    /**
     * <code>.bigsciencequiz.GameState newState = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getNewStateOrBuilder() {
      return getNewState();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (newState_ != null) {
        output.writeMessage(1, getNewState());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (newState_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNewState());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent other = (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) obj;

      boolean result = true;
      result = result && (hasNewState() == other.hasNewState());
      if (hasNewState()) {
        result = result && getNewState()
            .equals(other.getNewState());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNewState()) {
        hash = (37 * hash) + NEWSTATE_FIELD_NUMBER;
        hash = (53 * hash) + getNewState().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.GameStateChangeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.GameStateChangeEvent)
        club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameStateChangeEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameStateChangeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.class, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (newStateBuilder_ == null) {
          newState_ = null;
        } else {
          newState_ = null;
          newStateBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameStateChangeEvent_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent build() {
        club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent buildPartial() {
        club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent result = new club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent(this);
        if (newStateBuilder_ == null) {
          result.newState_ = newState_;
        } else {
          result.newState_ = newStateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent other) {
        if (other == club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance()) return this;
        if (other.hasNewState()) {
          mergeNewState(other.getNewState());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private club.eslcc.bigsciencequiz.proto.Gamestate.GameState newState_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder> newStateBuilder_;
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public boolean hasNewState() {
        return newStateBuilder_ != null || newState_ != null;
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState getNewState() {
        if (newStateBuilder_ == null) {
          return newState_ == null ? club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : newState_;
        } else {
          return newStateBuilder_.getMessage();
        }
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public Builder setNewState(club.eslcc.bigsciencequiz.proto.Gamestate.GameState value) {
        if (newStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newState_ = value;
          onChanged();
        } else {
          newStateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public Builder setNewState(
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder builderForValue) {
        if (newStateBuilder_ == null) {
          newState_ = builderForValue.build();
          onChanged();
        } else {
          newStateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public Builder mergeNewState(club.eslcc.bigsciencequiz.proto.Gamestate.GameState value) {
        if (newStateBuilder_ == null) {
          if (newState_ != null) {
            newState_ =
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.newBuilder(newState_).mergeFrom(value).buildPartial();
          } else {
            newState_ = value;
          }
          onChanged();
        } else {
          newStateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public Builder clearNewState() {
        if (newStateBuilder_ == null) {
          newState_ = null;
          onChanged();
        } else {
          newState_ = null;
          newStateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder getNewStateBuilder() {
        
        onChanged();
        return getNewStateFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder getNewStateOrBuilder() {
        if (newStateBuilder_ != null) {
          return newStateBuilder_.getMessageOrBuilder();
        } else {
          return newState_ == null ?
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState.getDefaultInstance() : newState_;
        }
      }
      /**
       * <code>.bigsciencequiz.GameState newState = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder> 
          getNewStateFieldBuilder() {
        if (newStateBuilder_ == null) {
          newStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.Gamestate.GameState, club.eslcc.bigsciencequiz.proto.Gamestate.GameState.Builder, club.eslcc.bigsciencequiz.proto.Gamestate.GameStateOrBuilder>(
                  getNewState(),
                  getParentForChildren(),
                  isClean());
          newState_ = null;
        }
        return newStateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.GameStateChangeEvent)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.GameStateChangeEvent)
    private static final club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent();
    }

    public static club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameStateChangeEvent>
        PARSER = new com.google.protobuf.AbstractParser<GameStateChangeEvent>() {
      public GameStateChangeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GameStateChangeEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameStateChangeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameStateChangeEvent> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ErrorEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.ErrorEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string description = 1;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 1;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code bigsciencequiz.ErrorEvent}
   */
  public  static final class ErrorEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.ErrorEvent)
      ErrorEventOrBuilder {
    // Use ErrorEvent.newBuilder() to construct.
    private ErrorEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorEvent() {
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ErrorEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_ErrorEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_ErrorEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.class, club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder.class);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 1;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, description_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, description_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.Events.ErrorEvent)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.Events.ErrorEvent other = (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) obj;

      boolean result = true;
      result = result && getDescription()
          .equals(other.getDescription());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.Events.ErrorEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.ErrorEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.ErrorEvent)
        club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_ErrorEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_ErrorEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.class, club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        description_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_ErrorEvent_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent build() {
        club.eslcc.bigsciencequiz.proto.Events.ErrorEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent buildPartial() {
        club.eslcc.bigsciencequiz.proto.Events.ErrorEvent result = new club.eslcc.bigsciencequiz.proto.Events.ErrorEvent(this);
        result.description_ = description_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.Events.ErrorEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.Events.ErrorEvent other) {
        if (other == club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance()) return this;
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.Events.ErrorEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 1;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.ErrorEvent)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.ErrorEvent)
    private static final club.eslcc.bigsciencequiz.proto.Events.ErrorEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.Events.ErrorEvent();
    }

    public static club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorEvent>
        PARSER = new com.google.protobuf.AbstractParser<ErrorEvent>() {
      public ErrorEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ErrorEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ErrorEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorEvent> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.GameEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getGameStateChangeEvent();
    /**
     * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder getGameStateChangeEventOrBuilder();

    /**
     * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getErrorEvent();
    /**
     * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
     */
    club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder getErrorEventOrBuilder();

    /**
     * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getAdminDevicesChangedEvent();
    /**
     * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder getAdminDevicesChangedEventOrBuilder();

    /**
     * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent getAdminQuestionsChangedEvent();
    /**
     * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder getAdminQuestionsChangedEventOrBuilder();

    public club.eslcc.bigsciencequiz.proto.Events.GameEvent.EventCase getEventCase();
  }
  /**
   * Protobuf type {@code bigsciencequiz.GameEvent}
   */
  public  static final class GameEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.GameEvent)
      GameEventOrBuilder {
    // Use GameEvent.newBuilder() to construct.
    private GameEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GameEvent() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GameEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder subBuilder = null;
              if (eventCase_ == 1) {
                subBuilder = ((club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 1;
              break;
            }
            case 18: {
              club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder subBuilder = null;
              if (eventCase_ == 2) {
                subBuilder = ((club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 2;
              break;
            }
            case 26: {
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder subBuilder = null;
              if (eventCase_ == 3) {
                subBuilder = ((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 3;
              break;
            }
            case 34: {
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder subBuilder = null;
              if (eventCase_ == 4) {
                subBuilder = ((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_).toBuilder();
              }
              event_ =
                  input.readMessage(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_);
                event_ = subBuilder.buildPartial();
              }
              eventCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.Events.GameEvent.class, club.eslcc.bigsciencequiz.proto.Events.GameEvent.Builder.class);
    }

    private int eventCase_ = 0;
    private java.lang.Object event_;
    public enum EventCase
        implements com.google.protobuf.Internal.EnumLite {
      GAMESTATECHANGEEVENT(1),
      ERROREVENT(2),
      ADMINDEVICESCHANGEDEVENT(3),
      ADMINQUESTIONSCHANGEDEVENT(4),
      EVENT_NOT_SET(0);
      private final int value;
      private EventCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EventCase valueOf(int value) {
        return forNumber(value);
      }

      public static EventCase forNumber(int value) {
        switch (value) {
          case 1: return GAMESTATECHANGEEVENT;
          case 2: return ERROREVENT;
          case 3: return ADMINDEVICESCHANGEDEVENT;
          case 4: return ADMINQUESTIONSCHANGEDEVENT;
          case 0: return EVENT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventCase
    getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public static final int GAMESTATECHANGEEVENT_FIELD_NUMBER = 1;
    /**
     * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getGameStateChangeEvent() {
      if (eventCase_ == 1) {
         return (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
    }
    /**
     * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder getGameStateChangeEventOrBuilder() {
      if (eventCase_ == 1) {
         return (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
    }

    public static final int ERROREVENT_FIELD_NUMBER = 2;
    /**
     * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getErrorEvent() {
      if (eventCase_ == 2) {
         return (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
    }
    /**
     * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
     */
    public club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder getErrorEventOrBuilder() {
      if (eventCase_ == 2) {
         return (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
    }

    public static final int ADMINDEVICESCHANGEDEVENT_FIELD_NUMBER = 3;
    /**
     * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getAdminDevicesChangedEvent() {
      if (eventCase_ == 3) {
         return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
    }
    /**
     * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder getAdminDevicesChangedEventOrBuilder() {
      if (eventCase_ == 3) {
         return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
    }

    public static final int ADMINQUESTIONSCHANGEDEVENT_FIELD_NUMBER = 4;
    /**
     * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent getAdminQuestionsChangedEvent() {
      if (eventCase_ == 4) {
         return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
    }
    /**
     * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder getAdminQuestionsChangedEventOrBuilder() {
      if (eventCase_ == 4) {
         return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_;
      }
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventCase_ == 1) {
        output.writeMessage(1, (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_);
      }
      if (eventCase_ == 2) {
        output.writeMessage(2, (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_);
      }
      if (eventCase_ == 3) {
        output.writeMessage(3, (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_);
      }
      if (eventCase_ == 4) {
        output.writeMessage(4, (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_);
      }
      if (eventCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_);
      }
      if (eventCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_);
      }
      if (eventCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.Events.GameEvent)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.Events.GameEvent other = (club.eslcc.bigsciencequiz.proto.Events.GameEvent) obj;

      boolean result = true;
      result = result && getEventCase().equals(
          other.getEventCase());
      if (!result) return false;
      switch (eventCase_) {
        case 1:
          result = result && getGameStateChangeEvent()
              .equals(other.getGameStateChangeEvent());
          break;
        case 2:
          result = result && getErrorEvent()
              .equals(other.getErrorEvent());
          break;
        case 3:
          result = result && getAdminDevicesChangedEvent()
              .equals(other.getAdminDevicesChangedEvent());
          break;
        case 4:
          result = result && getAdminQuestionsChangedEvent()
              .equals(other.getAdminQuestionsChangedEvent());
          break;
        case 0:
        default:
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (eventCase_) {
        case 1:
          hash = (37 * hash) + GAMESTATECHANGEEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getGameStateChangeEvent().hashCode();
          break;
        case 2:
          hash = (37 * hash) + ERROREVENT_FIELD_NUMBER;
          hash = (53 * hash) + getErrorEvent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ADMINDEVICESCHANGEDEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getAdminDevicesChangedEvent().hashCode();
          break;
        case 4:
          hash = (37 * hash) + ADMINQUESTIONSCHANGEDEVENT_FIELD_NUMBER;
          hash = (53 * hash) + getAdminQuestionsChangedEvent().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.Events.GameEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.GameEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.GameEvent)
        club.eslcc.bigsciencequiz.proto.Events.GameEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.Events.GameEvent.class, club.eslcc.bigsciencequiz.proto.Events.GameEvent.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.Events.GameEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        eventCase_ = 0;
        event_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.Events.internal_static_bigsciencequiz_GameEvent_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameEvent getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.Events.GameEvent.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameEvent build() {
        club.eslcc.bigsciencequiz.proto.Events.GameEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.Events.GameEvent buildPartial() {
        club.eslcc.bigsciencequiz.proto.Events.GameEvent result = new club.eslcc.bigsciencequiz.proto.Events.GameEvent(this);
        if (eventCase_ == 1) {
          if (gameStateChangeEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = gameStateChangeEventBuilder_.build();
          }
        }
        if (eventCase_ == 2) {
          if (errorEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = errorEventBuilder_.build();
          }
        }
        if (eventCase_ == 3) {
          if (adminDevicesChangedEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = adminDevicesChangedEventBuilder_.build();
          }
        }
        if (eventCase_ == 4) {
          if (adminQuestionsChangedEventBuilder_ == null) {
            result.event_ = event_;
          } else {
            result.event_ = adminQuestionsChangedEventBuilder_.build();
          }
        }
        result.eventCase_ = eventCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.Events.GameEvent) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.Events.GameEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.Events.GameEvent other) {
        if (other == club.eslcc.bigsciencequiz.proto.Events.GameEvent.getDefaultInstance()) return this;
        switch (other.getEventCase()) {
          case GAMESTATECHANGEEVENT: {
            mergeGameStateChangeEvent(other.getGameStateChangeEvent());
            break;
          }
          case ERROREVENT: {
            mergeErrorEvent(other.getErrorEvent());
            break;
          }
          case ADMINDEVICESCHANGEDEVENT: {
            mergeAdminDevicesChangedEvent(other.getAdminDevicesChangedEvent());
            break;
          }
          case ADMINQUESTIONSCHANGEDEVENT: {
            mergeAdminQuestionsChangedEvent(other.getAdminQuestionsChangedEvent());
            break;
          }
          case EVENT_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.Events.GameEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.Events.GameEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventCase_ = 0;
      private java.lang.Object event_;
      public EventCase
          getEventCase() {
        return EventCase.forNumber(
            eventCase_);
      }

      public Builder clearEvent() {
        eventCase_ = 0;
        event_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder> gameStateChangeEventBuilder_;
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent getGameStateChangeEvent() {
        if (gameStateChangeEventBuilder_ == null) {
          if (eventCase_ == 1) {
            return (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 1) {
            return gameStateChangeEventBuilder_.getMessage();
          }
          return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public Builder setGameStateChangeEvent(club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent value) {
        if (gameStateChangeEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          gameStateChangeEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public Builder setGameStateChangeEvent(
          club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder builderForValue) {
        if (gameStateChangeEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          gameStateChangeEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public Builder mergeGameStateChangeEvent(club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent value) {
        if (gameStateChangeEventBuilder_ == null) {
          if (eventCase_ == 1 &&
              event_ != club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance()) {
            event_ = club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.newBuilder((club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 1) {
            gameStateChangeEventBuilder_.mergeFrom(value);
          }
          gameStateChangeEventBuilder_.setMessage(value);
        }
        eventCase_ = 1;
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public Builder clearGameStateChangeEvent() {
        if (gameStateChangeEventBuilder_ == null) {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 1) {
            eventCase_ = 0;
            event_ = null;
          }
          gameStateChangeEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder getGameStateChangeEventBuilder() {
        return getGameStateChangeEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder getGameStateChangeEventOrBuilder() {
        if ((eventCase_ == 1) && (gameStateChangeEventBuilder_ != null)) {
          return gameStateChangeEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 1) {
            return (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.GameStateChangeEvent gameStateChangeEvent = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder> 
          getGameStateChangeEventFieldBuilder() {
        if (gameStateChangeEventBuilder_ == null) {
          if (!(eventCase_ == 1)) {
            event_ = club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.getDefaultInstance();
          }
          gameStateChangeEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEventOrBuilder>(
                  (club.eslcc.bigsciencequiz.proto.Events.GameStateChangeEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 1;
        onChanged();;
        return gameStateChangeEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Events.ErrorEvent, club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder> errorEventBuilder_;
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent getErrorEvent() {
        if (errorEventBuilder_ == null) {
          if (eventCase_ == 2) {
            return (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 2) {
            return errorEventBuilder_.getMessage();
          }
          return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public Builder setErrorEvent(club.eslcc.bigsciencequiz.proto.Events.ErrorEvent value) {
        if (errorEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          errorEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public Builder setErrorEvent(
          club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder builderForValue) {
        if (errorEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          errorEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public Builder mergeErrorEvent(club.eslcc.bigsciencequiz.proto.Events.ErrorEvent value) {
        if (errorEventBuilder_ == null) {
          if (eventCase_ == 2 &&
              event_ != club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance()) {
            event_ = club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.newBuilder((club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 2) {
            errorEventBuilder_.mergeFrom(value);
          }
          errorEventBuilder_.setMessage(value);
        }
        eventCase_ = 2;
        return this;
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public Builder clearErrorEvent() {
        if (errorEventBuilder_ == null) {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 2) {
            eventCase_ = 0;
            event_ = null;
          }
          errorEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder getErrorEventBuilder() {
        return getErrorEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      public club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder getErrorEventOrBuilder() {
        if ((eventCase_ == 2) && (errorEventBuilder_ != null)) {
          return errorEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 2) {
            return (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.ErrorEvent errorEvent = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.Events.ErrorEvent, club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder> 
          getErrorEventFieldBuilder() {
        if (errorEventBuilder_ == null) {
          if (!(eventCase_ == 2)) {
            event_ = club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.getDefaultInstance();
          }
          errorEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.Events.ErrorEvent, club.eslcc.bigsciencequiz.proto.Events.ErrorEvent.Builder, club.eslcc.bigsciencequiz.proto.Events.ErrorEventOrBuilder>(
                  (club.eslcc.bigsciencequiz.proto.Events.ErrorEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 2;
        onChanged();;
        return errorEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder> adminDevicesChangedEventBuilder_;
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getAdminDevicesChangedEvent() {
        if (adminDevicesChangedEventBuilder_ == null) {
          if (eventCase_ == 3) {
            return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 3) {
            return adminDevicesChangedEventBuilder_.getMessage();
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public Builder setAdminDevicesChangedEvent(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent value) {
        if (adminDevicesChangedEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          adminDevicesChangedEventBuilder_.setMessage(value);
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public Builder setAdminDevicesChangedEvent(
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder builderForValue) {
        if (adminDevicesChangedEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          adminDevicesChangedEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public Builder mergeAdminDevicesChangedEvent(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent value) {
        if (adminDevicesChangedEventBuilder_ == null) {
          if (eventCase_ == 3 &&
              event_ != club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance()) {
            event_ = club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.newBuilder((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 3) {
            adminDevicesChangedEventBuilder_.mergeFrom(value);
          }
          adminDevicesChangedEventBuilder_.setMessage(value);
        }
        eventCase_ = 3;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public Builder clearAdminDevicesChangedEvent() {
        if (adminDevicesChangedEventBuilder_ == null) {
          if (eventCase_ == 3) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 3) {
            eventCase_ = 0;
            event_ = null;
          }
          adminDevicesChangedEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder getAdminDevicesChangedEventBuilder() {
        return getAdminDevicesChangedEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder getAdminDevicesChangedEventOrBuilder() {
        if ((eventCase_ == 3) && (adminDevicesChangedEventBuilder_ != null)) {
          return adminDevicesChangedEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 3) {
            return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.admin.AdminDevicesChangedEvent adminDevicesChangedEvent = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder> 
          getAdminDevicesChangedEventFieldBuilder() {
        if (adminDevicesChangedEventBuilder_ == null) {
          if (!(eventCase_ == 3)) {
            event_ = club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
          }
          adminDevicesChangedEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder>(
                  (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 3;
        onChanged();;
        return adminDevicesChangedEventBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder> adminQuestionsChangedEventBuilder_;
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent getAdminQuestionsChangedEvent() {
        if (adminQuestionsChangedEventBuilder_ == null) {
          if (eventCase_ == 4) {
            return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
        } else {
          if (eventCase_ == 4) {
            return adminQuestionsChangedEventBuilder_.getMessage();
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public Builder setAdminQuestionsChangedEvent(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent value) {
        if (adminQuestionsChangedEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          event_ = value;
          onChanged();
        } else {
          adminQuestionsChangedEventBuilder_.setMessage(value);
        }
        eventCase_ = 4;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public Builder setAdminQuestionsChangedEvent(
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder builderForValue) {
        if (adminQuestionsChangedEventBuilder_ == null) {
          event_ = builderForValue.build();
          onChanged();
        } else {
          adminQuestionsChangedEventBuilder_.setMessage(builderForValue.build());
        }
        eventCase_ = 4;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public Builder mergeAdminQuestionsChangedEvent(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent value) {
        if (adminQuestionsChangedEventBuilder_ == null) {
          if (eventCase_ == 4 &&
              event_ != club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance()) {
            event_ = club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.newBuilder((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_)
                .mergeFrom(value).buildPartial();
          } else {
            event_ = value;
          }
          onChanged();
        } else {
          if (eventCase_ == 4) {
            adminQuestionsChangedEventBuilder_.mergeFrom(value);
          }
          adminQuestionsChangedEventBuilder_.setMessage(value);
        }
        eventCase_ = 4;
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public Builder clearAdminQuestionsChangedEvent() {
        if (adminQuestionsChangedEventBuilder_ == null) {
          if (eventCase_ == 4) {
            eventCase_ = 0;
            event_ = null;
            onChanged();
          }
        } else {
          if (eventCase_ == 4) {
            eventCase_ = 0;
            event_ = null;
          }
          adminQuestionsChangedEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder getAdminQuestionsChangedEventBuilder() {
        return getAdminQuestionsChangedEventFieldBuilder().getBuilder();
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder getAdminQuestionsChangedEventOrBuilder() {
        if ((eventCase_ == 4) && (adminQuestionsChangedEventBuilder_ != null)) {
          return adminQuestionsChangedEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventCase_ == 4) {
            return (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_;
          }
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
        }
      }
      /**
       * <code>.bigsciencequiz.admin.AdminQuestionsChangedEvent adminQuestionsChangedEvent = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder> 
          getAdminQuestionsChangedEventFieldBuilder() {
        if (adminQuestionsChangedEventBuilder_ == null) {
          if (!(eventCase_ == 4)) {
            event_ = club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.getDefaultInstance();
          }
          adminQuestionsChangedEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEventOrBuilder>(
                  (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminQuestionsChangedEvent) event_,
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        eventCase_ = 4;
        onChanged();;
        return adminQuestionsChangedEventBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.GameEvent)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.GameEvent)
    private static final club.eslcc.bigsciencequiz.proto.Events.GameEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.Events.GameEvent();
    }

    public static club.eslcc.bigsciencequiz.proto.Events.GameEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GameEvent>
        PARSER = new com.google.protobuf.AbstractParser<GameEvent>() {
      public GameEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GameEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GameEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameEvent> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.Events.GameEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_GameStateChangeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_GameStateChangeEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_ErrorEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_ErrorEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_GameEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_GameEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014events.proto\022\016bigsciencequiz\032\022admin_ev" +
      "ents.proto\032\016question.proto\032\017gamestate.pr" +
      "oto\"C\n\024GameStateChangeEvent\022+\n\010newState\030" +
      "\001 \001(\0132\031.bigsciencequiz.GameState\"!\n\nErro" +
      "rEvent\022\023\n\013description\030\001 \001(\t\"\270\002\n\tGameEven" +
      "t\022D\n\024gameStateChangeEvent\030\001 \001(\0132$.bigsci" +
      "encequiz.GameStateChangeEventH\000\0220\n\nerror" +
      "Event\030\002 \001(\0132\032.bigsciencequiz.ErrorEventH" +
      "\000\022R\n\030adminDevicesChangedEvent\030\003 \001(\0132..bi" +
      "gsciencequiz.admin.AdminDevicesChangedEv",
      "entH\000\022V\n\032adminQuestionsChangedEvent\030\004 \001(" +
      "\01320.bigsciencequiz.admin.AdminQuestionsC" +
      "hangedEventH\000B\007\n\005eventB!\n\037club.eslcc.big" +
      "sciencequiz.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.getDescriptor(),
          club.eslcc.bigsciencequiz.proto.QuestionOuterClass.getDescriptor(),
          club.eslcc.bigsciencequiz.proto.Gamestate.getDescriptor(),
        }, assigner);
    internal_static_bigsciencequiz_GameStateChangeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bigsciencequiz_GameStateChangeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_GameStateChangeEvent_descriptor,
        new java.lang.String[] { "NewState", });
    internal_static_bigsciencequiz_ErrorEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bigsciencequiz_ErrorEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_ErrorEvent_descriptor,
        new java.lang.String[] { "Description", });
    internal_static_bigsciencequiz_GameEvent_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bigsciencequiz_GameEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_GameEvent_descriptor,
        new java.lang.String[] { "GameStateChangeEvent", "ErrorEvent", "AdminDevicesChangedEvent", "AdminQuestionsChangedEvent", "Event", });
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.getDescriptor();
    club.eslcc.bigsciencequiz.proto.QuestionOuterClass.getDescriptor();
    club.eslcc.bigsciencequiz.proto.Gamestate.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
