version: '2'
services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./live/redis-data/:/data

  sentry_redis:
    image: redis

  lb:
    build: ./nginx
    ports:
     - "8080:80"
    depends_on:
     - app

  postgres:
    image: postgres
    volumes:
     - postgres-db-volume:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sentry

  sentry:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    links:
     - sentry_redis
     - postgres
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis

  sentry_worker:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    command: "sentry run worker"
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis
      C_FORCE_ROOT: 1
  
  prometheus-server:
    image: prom/prometheus
    expose:
      - "9090"
    ports:
      - 9090:9090
    links:
      - prometheus_redis_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  prometheus_redis_exporter:
    image: oliver006/redis_exporter
    links:
      - redis
    environment:
      REDIS_ADDR: redis:6379
      
  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus

  sentry_cron:
    image: sentry:latest
    depends_on:
     - sentry_redis
     - postgres
    command: "sentry run cron"
    environment:
      SENTRY_SECRET_KEY: P1fsr0VZanfGVFCMacYpxGI9LGhFMjvj7MdOy5N6
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: sentry_redis
      C_FORCE_ROOT: 1

  app:
    build: ./app
    depends_on:
      - redis
    environment:
      SENTRY_DSN: "http://0a74bfd71a9f42dfa702ce980117733c:2dc376ac4da045f78cfa15b970500ca4@sentry:9000/2"
      
volumes:
  postgres-db-volume:
      
