// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: admin_events.proto

package club.eslcc.bigsciencequiz.proto.admin;

public final class AdminEvents {
  private AdminEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdminDevicesChangedEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.admin.AdminDevicesChangedEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> 
        getDevicesList();
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDevices(int index);
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    int getDevicesCount();
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    java.util.List<? extends club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder> 
        getDevicesOrBuilderList();
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder getDevicesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bigsciencequiz.admin.AdminDevicesChangedEvent}
   */
  public  static final class AdminDevicesChangedEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.admin.AdminDevicesChangedEvent)
      AdminDevicesChangedEventOrBuilder {
    // Use AdminDevicesChangedEvent.newBuilder() to construct.
    private AdminDevicesChangedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdminDevicesChangedEvent() {
      devices_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AdminDevicesChangedEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                devices_ = new java.util.ArrayList<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device>();
                mutable_bitField0_ |= 0x00000001;
              }
              devices_.add(
                  input.readMessage(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          devices_ = java.util.Collections.unmodifiableList(devices_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.class, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder.class);
    }

    public interface DeviceOrBuilder extends
        // @@protoc_insertion_point(interface_extends:bigsciencequiz.admin.AdminDevicesChangedEvent.Device)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string deviceId = 1;</code>
       */
      java.lang.String getDeviceId();
      /**
       * <code>string deviceId = 1;</code>
       */
      com.google.protobuf.ByteString
          getDeviceIdBytes();

      /**
       * <code>int32 team = 2;</code>
       */
      int getTeam();

      /**
       * <code>bool ready = 3;</code>
       */
      boolean getReady();
    }
    /**
     * Protobuf type {@code bigsciencequiz.admin.AdminDevicesChangedEvent.Device}
     */
    public  static final class Device extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:bigsciencequiz.admin.AdminDevicesChangedEvent.Device)
        DeviceOrBuilder {
      // Use Device.newBuilder() to construct.
      private Device(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Device() {
        deviceId_ = "";
        team_ = 0;
        ready_ = false;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private Device(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                deviceId_ = s;
                break;
              }
              case 16: {

                team_ = input.readInt32();
                break;
              }
              case 24: {

                ready_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.class, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder.class);
      }

      public static final int DEVICEID_FIELD_NUMBER = 1;
      private volatile java.lang.Object deviceId_;
      /**
       * <code>string deviceId = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TEAM_FIELD_NUMBER = 2;
      private int team_;
      /**
       * <code>int32 team = 2;</code>
       */
      public int getTeam() {
        return team_;
      }

      public static final int READY_FIELD_NUMBER = 3;
      private boolean ready_;
      /**
       * <code>bool ready = 3;</code>
       */
      public boolean getReady() {
        return ready_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getDeviceIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
        }
        if (team_ != 0) {
          output.writeInt32(2, team_);
        }
        if (ready_ != false) {
          output.writeBool(3, ready_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDeviceIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
        }
        if (team_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, team_);
        }
        if (ready_ != false) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, ready_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device)) {
          return super.equals(obj);
        }
        club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device other = (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device) obj;

        boolean result = true;
        result = result && getDeviceId()
            .equals(other.getDeviceId());
        result = result && (getTeam()
            == other.getTeam());
        result = result && (getReady()
            == other.getReady());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceId().hashCode();
        hash = (37 * hash) + TEAM_FIELD_NUMBER;
        hash = (53 * hash) + getTeam();
        hash = (37 * hash) + READY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReady());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code bigsciencequiz.admin.AdminDevicesChangedEvent.Device}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:bigsciencequiz.admin.AdminDevicesChangedEvent.Device)
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.class, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder.class);
        }

        // Construct using club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          deviceId_ = "";

          team_ = 0;

          ready_ = false;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor;
        }

        public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDefaultInstanceForType() {
          return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.getDefaultInstance();
        }

        public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device build() {
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device buildPartial() {
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device result = new club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device(this);
          result.deviceId_ = deviceId_;
          result.team_ = team_;
          result.ready_ = ready_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device) {
            return mergeFrom((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device other) {
          if (other == club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.getDefaultInstance()) return this;
          if (!other.getDeviceId().isEmpty()) {
            deviceId_ = other.deviceId_;
            onChanged();
          }
          if (other.getTeam() != 0) {
            setTeam(other.getTeam());
          }
          if (other.getReady() != false) {
            setReady(other.getReady());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object deviceId_ = "";
        /**
         * <code>string deviceId = 1;</code>
         */
        public java.lang.String getDeviceId() {
          java.lang.Object ref = deviceId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            deviceId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string deviceId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDeviceIdBytes() {
          java.lang.Object ref = deviceId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            deviceId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string deviceId = 1;</code>
         */
        public Builder setDeviceId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          deviceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string deviceId = 1;</code>
         */
        public Builder clearDeviceId() {
          
          deviceId_ = getDefaultInstance().getDeviceId();
          onChanged();
          return this;
        }
        /**
         * <code>string deviceId = 1;</code>
         */
        public Builder setDeviceIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          deviceId_ = value;
          onChanged();
          return this;
        }

        private int team_ ;
        /**
         * <code>int32 team = 2;</code>
         */
        public int getTeam() {
          return team_;
        }
        /**
         * <code>int32 team = 2;</code>
         */
        public Builder setTeam(int value) {
          
          team_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 team = 2;</code>
         */
        public Builder clearTeam() {
          
          team_ = 0;
          onChanged();
          return this;
        }

        private boolean ready_ ;
        /**
         * <code>bool ready = 3;</code>
         */
        public boolean getReady() {
          return ready_;
        }
        /**
         * <code>bool ready = 3;</code>
         */
        public Builder setReady(boolean value) {
          
          ready_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bool ready = 3;</code>
         */
        public Builder clearReady() {
          
          ready_ = false;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:bigsciencequiz.admin.AdminDevicesChangedEvent.Device)
      }

      // @@protoc_insertion_point(class_scope:bigsciencequiz.admin.AdminDevicesChangedEvent.Device)
      private static final club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device();
      }

      public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Device>
          PARSER = new com.google.protobuf.AbstractParser<Device>() {
        public Device parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Device(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Device> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Device> getParserForType() {
        return PARSER;
      }

      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DEVICES_FIELD_NUMBER = 1;
    private java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> devices_;
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    public java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> getDevicesList() {
      return devices_;
    }
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    public java.util.List<? extends club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder> 
        getDevicesOrBuilderList() {
      return devices_;
    }
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    public int getDevicesCount() {
      return devices_.size();
    }
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDevices(int index) {
      return devices_.get(index);
    }
    /**
     * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder getDevicesOrBuilder(
        int index) {
      return devices_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < devices_.size(); i++) {
        output.writeMessage(1, devices_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < devices_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, devices_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent other = (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) obj;

      boolean result = true;
      result = result && getDevicesList()
          .equals(other.getDevicesList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDevicesCount() > 0) {
        hash = (37 * hash) + DEVICES_FIELD_NUMBER;
        hash = (53 * hash) + getDevicesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.admin.AdminDevicesChangedEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.admin.AdminDevicesChangedEvent)
        club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.class, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDevicesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (devicesBuilder_ == null) {
          devices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          devicesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent build() {
        club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent buildPartial() {
        club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent result = new club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent(this);
        int from_bitField0_ = bitField0_;
        if (devicesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            devices_ = java.util.Collections.unmodifiableList(devices_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.devices_ = devices_;
        } else {
          result.devices_ = devicesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent other) {
        if (other == club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.getDefaultInstance()) return this;
        if (devicesBuilder_ == null) {
          if (!other.devices_.isEmpty()) {
            if (devices_.isEmpty()) {
              devices_ = other.devices_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDevicesIsMutable();
              devices_.addAll(other.devices_);
            }
            onChanged();
          }
        } else {
          if (!other.devices_.isEmpty()) {
            if (devicesBuilder_.isEmpty()) {
              devicesBuilder_.dispose();
              devicesBuilder_ = null;
              devices_ = other.devices_;
              bitField0_ = (bitField0_ & ~0x00000001);
              devicesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDevicesFieldBuilder() : null;
            } else {
              devicesBuilder_.addAllMessages(other.devices_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> devices_ =
        java.util.Collections.emptyList();
      private void ensureDevicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          devices_ = new java.util.ArrayList<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device>(devices_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder> devicesBuilder_;

      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> getDevicesList() {
        if (devicesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(devices_);
        } else {
          return devicesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public int getDevicesCount() {
        if (devicesBuilder_ == null) {
          return devices_.size();
        } else {
          return devicesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device getDevices(int index) {
        if (devicesBuilder_ == null) {
          return devices_.get(index);
        } else {
          return devicesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder setDevices(
          int index, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device value) {
        if (devicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesIsMutable();
          devices_.set(index, value);
          onChanged();
        } else {
          devicesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder setDevices(
          int index, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder builderForValue) {
        if (devicesBuilder_ == null) {
          ensureDevicesIsMutable();
          devices_.set(index, builderForValue.build());
          onChanged();
        } else {
          devicesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder addDevices(club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device value) {
        if (devicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesIsMutable();
          devices_.add(value);
          onChanged();
        } else {
          devicesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder addDevices(
          int index, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device value) {
        if (devicesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicesIsMutable();
          devices_.add(index, value);
          onChanged();
        } else {
          devicesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder addDevices(
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder builderForValue) {
        if (devicesBuilder_ == null) {
          ensureDevicesIsMutable();
          devices_.add(builderForValue.build());
          onChanged();
        } else {
          devicesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder addDevices(
          int index, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder builderForValue) {
        if (devicesBuilder_ == null) {
          ensureDevicesIsMutable();
          devices_.add(index, builderForValue.build());
          onChanged();
        } else {
          devicesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder addAllDevices(
          java.lang.Iterable<? extends club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device> values) {
        if (devicesBuilder_ == null) {
          ensureDevicesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, devices_);
          onChanged();
        } else {
          devicesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder clearDevices() {
        if (devicesBuilder_ == null) {
          devices_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          devicesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public Builder removeDevices(int index) {
        if (devicesBuilder_ == null) {
          ensureDevicesIsMutable();
          devices_.remove(index);
          onChanged();
        } else {
          devicesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder getDevicesBuilder(
          int index) {
        return getDevicesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder getDevicesOrBuilder(
          int index) {
        if (devicesBuilder_ == null) {
          return devices_.get(index);  } else {
          return devicesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public java.util.List<? extends club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder> 
           getDevicesOrBuilderList() {
        if (devicesBuilder_ != null) {
          return devicesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(devices_);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder addDevicesBuilder() {
        return getDevicesFieldBuilder().addBuilder(
            club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.getDefaultInstance());
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder addDevicesBuilder(
          int index) {
        return getDevicesFieldBuilder().addBuilder(
            index, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.getDefaultInstance());
      }
      /**
       * <code>repeated .bigsciencequiz.admin.AdminDevicesChangedEvent.Device devices = 1;</code>
       */
      public java.util.List<club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder> 
           getDevicesBuilderList() {
        return getDevicesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder> 
          getDevicesFieldBuilder() {
        if (devicesBuilder_ == null) {
          devicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.Device.Builder, club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent.DeviceOrBuilder>(
                  devices_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          devices_ = null;
        }
        return devicesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.admin.AdminDevicesChangedEvent)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.admin.AdminDevicesChangedEvent)
    private static final club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent();
    }

    public static club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdminDevicesChangedEvent>
        PARSER = new com.google.protobuf.AbstractParser<AdminDevicesChangedEvent>() {
      public AdminDevicesChangedEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AdminDevicesChangedEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdminDevicesChangedEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdminDevicesChangedEvent> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.admin.AdminEvents.AdminDevicesChangedEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022admin_events.proto\022\024bigsciencequiz.adm" +
      "in\"\233\001\n\030AdminDevicesChangedEvent\022F\n\007devic" +
      "es\030\001 \003(\01325.bigsciencequiz.admin.AdminDev" +
      "icesChangedEvent.Device\0327\n\006Device\022\020\n\010dev" +
      "iceId\030\001 \001(\t\022\014\n\004team\030\002 \001(\005\022\r\n\005ready\030\003 \001(\010" +
      "B\'\n%club.eslcc.bigsciencequiz.proto.admi" +
      "nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor,
        new java.lang.String[] { "Devices", });
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor =
      internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_descriptor.getNestedTypes().get(0);
    internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_admin_AdminDevicesChangedEvent_Device_descriptor,
        new java.lang.String[] { "DeviceId", "Team", "Ready", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
