# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/events.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from models import question_pb2 as models_dot_question__pb2
from models import gamestate_pb2 as models_dot_gamestate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='models/events.proto',
  package='bigsciencequiz',
  syntax='proto3',
  serialized_pb=_b('\n\x13models/events.proto\x12\x0e\x62igsciencequiz\x1a\x15models/question.proto\x1a\x16models/gamestate.proto\"C\n\x14GameStateChangeEvent\x12+\n\x08newState\x18\x01 \x01(\x0b\x32\x19.bigsciencequiz.GameState\"!\n\nErrorEvent\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x8c\x01\n\tGameEvent\x12\x44\n\x14gameStateChangeEvent\x18\x01 \x01(\x0b\x32$.bigsciencequiz.GameStateChangeEventH\x00\x12\x30\n\nerrorEvent\x18\x02 \x01(\x0b\x32\x1a.bigsciencequiz.ErrorEventH\x00\x42\x07\n\x05\x65ventB\x1b\n\x19\x63lub.eslcc.bigsciencequizb\x06proto3')
  ,
  dependencies=[models_dot_question__pb2.DESCRIPTOR,models_dot_gamestate__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GAMESTATECHANGEEVENT = _descriptor.Descriptor(
  name='GameStateChangeEvent',
  full_name='bigsciencequiz.GameStateChangeEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newState', full_name='bigsciencequiz.GameStateChangeEvent.newState', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=153,
)


_ERROREVENT = _descriptor.Descriptor(
  name='ErrorEvent',
  full_name='bigsciencequiz.ErrorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='bigsciencequiz.ErrorEvent.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=188,
)


_GAMEEVENT = _descriptor.Descriptor(
  name='GameEvent',
  full_name='bigsciencequiz.GameEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameStateChangeEvent', full_name='bigsciencequiz.GameEvent.gameStateChangeEvent', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorEvent', full_name='bigsciencequiz.GameEvent.errorEvent', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='bigsciencequiz.GameEvent.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=191,
  serialized_end=331,
)

_GAMESTATECHANGEEVENT.fields_by_name['newState'].message_type = models_dot_gamestate__pb2._GAMESTATE
_GAMEEVENT.fields_by_name['gameStateChangeEvent'].message_type = _GAMESTATECHANGEEVENT
_GAMEEVENT.fields_by_name['errorEvent'].message_type = _ERROREVENT
_GAMEEVENT.oneofs_by_name['event'].fields.append(
  _GAMEEVENT.fields_by_name['gameStateChangeEvent'])
_GAMEEVENT.fields_by_name['gameStateChangeEvent'].containing_oneof = _GAMEEVENT.oneofs_by_name['event']
_GAMEEVENT.oneofs_by_name['event'].fields.append(
  _GAMEEVENT.fields_by_name['errorEvent'])
_GAMEEVENT.fields_by_name['errorEvent'].containing_oneof = _GAMEEVENT.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['GameStateChangeEvent'] = _GAMESTATECHANGEEVENT
DESCRIPTOR.message_types_by_name['ErrorEvent'] = _ERROREVENT
DESCRIPTOR.message_types_by_name['GameEvent'] = _GAMEEVENT

GameStateChangeEvent = _reflection.GeneratedProtocolMessageType('GameStateChangeEvent', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATECHANGEEVENT,
  __module__ = 'models.events_pb2'
  # @@protoc_insertion_point(class_scope:bigsciencequiz.GameStateChangeEvent)
  ))
_sym_db.RegisterMessage(GameStateChangeEvent)

ErrorEvent = _reflection.GeneratedProtocolMessageType('ErrorEvent', (_message.Message,), dict(
  DESCRIPTOR = _ERROREVENT,
  __module__ = 'models.events_pb2'
  # @@protoc_insertion_point(class_scope:bigsciencequiz.ErrorEvent)
  ))
_sym_db.RegisterMessage(ErrorEvent)

GameEvent = _reflection.GeneratedProtocolMessageType('GameEvent', (_message.Message,), dict(
  DESCRIPTOR = _GAMEEVENT,
  __module__ = 'models.events_pb2'
  # @@protoc_insertion_point(class_scope:bigsciencequiz.GameEvent)
  ))
_sym_db.RegisterMessage(GameEvent)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031club.eslcc.bigsciencequiz'))
# @@protoc_insertion_point(module_scope)
