// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bigscreen_rpc.proto

package club.eslcc.bigsciencequiz.proto.bigscreen;

public final class BigscreenRpc {
  private BigscreenRpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BigscreenGetTeamsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.bigscreen.BigscreenGetTeamsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code bigsciencequiz.bigscreen.BigscreenGetTeamsRequest}
   */
  public  static final class BigscreenGetTeamsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.bigscreen.BigscreenGetTeamsRequest)
      BigscreenGetTeamsRequestOrBuilder {
    // Use BigscreenGetTeamsRequest.newBuilder() to construct.
    private BigscreenGetTeamsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BigscreenGetTeamsRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BigscreenGetTeamsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.class, club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest other = (club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest) obj;

      boolean result = true;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.bigscreen.BigscreenGetTeamsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.bigscreen.BigscreenGetTeamsRequest)
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.class, club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest build() {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest buildPartial() {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest result = new club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest other) {
        if (other == club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.bigscreen.BigscreenGetTeamsRequest)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.bigscreen.BigscreenGetTeamsRequest)
    private static final club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest();
    }

    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BigscreenGetTeamsRequest>
        PARSER = new com.google.protobuf.AbstractParser<BigscreenGetTeamsRequest>() {
      public BigscreenGetTeamsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BigscreenGetTeamsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BigscreenGetTeamsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BigscreenGetTeamsRequest> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BigscreenGetTeamsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bigsciencequiz.bigscreen.BigscreenGetTeamsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    java.util.List<club.eslcc.bigsciencequiz.proto.User.Team> 
        getTeamsList();
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.User.Team getTeams(int index);
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    int getTeamsCount();
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    java.util.List<? extends club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> 
        getTeamsOrBuilderList();
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bigsciencequiz.bigscreen.BigscreenGetTeamsResponse}
   */
  public  static final class BigscreenGetTeamsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bigsciencequiz.bigscreen.BigscreenGetTeamsResponse)
      BigscreenGetTeamsResponseOrBuilder {
    // Use BigscreenGetTeamsResponse.newBuilder() to construct.
    private BigscreenGetTeamsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BigscreenGetTeamsResponse() {
      teams_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BigscreenGetTeamsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                teams_ = new java.util.ArrayList<club.eslcc.bigsciencequiz.proto.User.Team>();
                mutable_bitField0_ |= 0x00000001;
              }
              teams_.add(
                  input.readMessage(club.eslcc.bigsciencequiz.proto.User.Team.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          teams_ = java.util.Collections.unmodifiableList(teams_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.class, club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.Builder.class);
    }

    public static final int TEAMS_FIELD_NUMBER = 1;
    private java.util.List<club.eslcc.bigsciencequiz.proto.User.Team> teams_;
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    public java.util.List<club.eslcc.bigsciencequiz.proto.User.Team> getTeamsList() {
      return teams_;
    }
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    public java.util.List<? extends club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> 
        getTeamsOrBuilderList() {
      return teams_;
    }
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    public int getTeamsCount() {
      return teams_.size();
    }
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.User.Team getTeams(int index) {
      return teams_.get(index);
    }
    /**
     * <code>repeated .bigsciencequiz.Team teams = 1;</code>
     */
    public club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamsOrBuilder(
        int index) {
      return teams_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < teams_.size(); i++) {
        output.writeMessage(1, teams_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < teams_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, teams_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse)) {
        return super.equals(obj);
      }
      club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse other = (club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse) obj;

      boolean result = true;
      result = result && getTeamsList()
          .equals(other.getTeamsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTeamsCount() > 0) {
        hash = (37 * hash) + TEAMS_FIELD_NUMBER;
        hash = (53 * hash) + getTeamsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bigsciencequiz.bigscreen.BigscreenGetTeamsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bigsciencequiz.bigscreen.BigscreenGetTeamsResponse)
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.class, club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.Builder.class);
      }

      // Construct using club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeamsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor;
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse getDefaultInstanceForType() {
        return club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.getDefaultInstance();
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse build() {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse buildPartial() {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse result = new club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse(this);
        int from_bitField0_ = bitField0_;
        if (teamsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            teams_ = java.util.Collections.unmodifiableList(teams_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teams_ = teams_;
        } else {
          result.teams_ = teamsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse) {
          return mergeFrom((club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse other) {
        if (other == club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse.getDefaultInstance()) return this;
        if (teamsBuilder_ == null) {
          if (!other.teams_.isEmpty()) {
            if (teams_.isEmpty()) {
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTeamsIsMutable();
              teams_.addAll(other.teams_);
            }
            onChanged();
          }
        } else {
          if (!other.teams_.isEmpty()) {
            if (teamsBuilder_.isEmpty()) {
              teamsBuilder_.dispose();
              teamsBuilder_ = null;
              teams_ = other.teams_;
              bitField0_ = (bitField0_ & ~0x00000001);
              teamsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeamsFieldBuilder() : null;
            } else {
              teamsBuilder_.addAllMessages(other.teams_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<club.eslcc.bigsciencequiz.proto.User.Team> teams_ =
        java.util.Collections.emptyList();
      private void ensureTeamsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          teams_ = new java.util.ArrayList<club.eslcc.bigsciencequiz.proto.User.Team>(teams_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> teamsBuilder_;

      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public java.util.List<club.eslcc.bigsciencequiz.proto.User.Team> getTeamsList() {
        if (teamsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teams_);
        } else {
          return teamsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public int getTeamsCount() {
        if (teamsBuilder_ == null) {
          return teams_.size();
        } else {
          return teamsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team getTeams(int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);
        } else {
          return teamsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, club.eslcc.bigsciencequiz.proto.User.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.set(index, value);
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder setTeams(
          int index, club.eslcc.bigsciencequiz.proto.User.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.set(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder addTeams(club.eslcc.bigsciencequiz.proto.User.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, club.eslcc.bigsciencequiz.proto.User.Team value) {
        if (teamsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeamsIsMutable();
          teams_.add(index, value);
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder addTeams(
          club.eslcc.bigsciencequiz.proto.User.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder addTeams(
          int index, club.eslcc.bigsciencequiz.proto.User.Team.Builder builderForValue) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.add(index, builderForValue.build());
          onChanged();
        } else {
          teamsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder addAllTeams(
          java.lang.Iterable<? extends club.eslcc.bigsciencequiz.proto.User.Team> values) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teams_);
          onChanged();
        } else {
          teamsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder clearTeams() {
        if (teamsBuilder_ == null) {
          teams_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teamsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public Builder removeTeams(int index) {
        if (teamsBuilder_ == null) {
          ensureTeamsIsMutable();
          teams_.remove(index);
          onChanged();
        } else {
          teamsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team.Builder getTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder getTeamsOrBuilder(
          int index) {
        if (teamsBuilder_ == null) {
          return teams_.get(index);  } else {
          return teamsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public java.util.List<? extends club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> 
           getTeamsOrBuilderList() {
        if (teamsBuilder_ != null) {
          return teamsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teams_);
        }
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team.Builder addTeamsBuilder() {
        return getTeamsFieldBuilder().addBuilder(
            club.eslcc.bigsciencequiz.proto.User.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public club.eslcc.bigsciencequiz.proto.User.Team.Builder addTeamsBuilder(
          int index) {
        return getTeamsFieldBuilder().addBuilder(
            index, club.eslcc.bigsciencequiz.proto.User.Team.getDefaultInstance());
      }
      /**
       * <code>repeated .bigsciencequiz.Team teams = 1;</code>
       */
      public java.util.List<club.eslcc.bigsciencequiz.proto.User.Team.Builder> 
           getTeamsBuilderList() {
        return getTeamsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder> 
          getTeamsFieldBuilder() {
        if (teamsBuilder_ == null) {
          teamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              club.eslcc.bigsciencequiz.proto.User.Team, club.eslcc.bigsciencequiz.proto.User.Team.Builder, club.eslcc.bigsciencequiz.proto.User.TeamOrBuilder>(
                  teams_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          teams_ = null;
        }
        return teamsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bigsciencequiz.bigscreen.BigscreenGetTeamsResponse)
    }

    // @@protoc_insertion_point(class_scope:bigsciencequiz.bigscreen.BigscreenGetTeamsResponse)
    private static final club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse();
    }

    public static club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BigscreenGetTeamsResponse>
        PARSER = new com.google.protobuf.AbstractParser<BigscreenGetTeamsResponse>() {
      public BigscreenGetTeamsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BigscreenGetTeamsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BigscreenGetTeamsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BigscreenGetTeamsResponse> getParserForType() {
      return PARSER;
    }

    public club.eslcc.bigsciencequiz.proto.bigscreen.BigscreenRpc.BigscreenGetTeamsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bigscreen_rpc.proto\022\030bigsciencequiz.bi" +
      "gscreen\032\nuser.proto\"\032\n\030BigscreenGetTeams" +
      "Request\"@\n\031BigscreenGetTeamsResponse\022#\n\005" +
      "teams\030\001 \003(\0132\024.bigsciencequiz.TeamB+\n)clu" +
      "b.eslcc.bigsciencequiz.proto.bigscreenb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          club.eslcc.bigsciencequiz.proto.User.getDescriptor(),
        }, assigner);
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bigsciencequiz_bigscreen_BigscreenGetTeamsResponse_descriptor,
        new java.lang.String[] { "Teams", });
    club.eslcc.bigsciencequiz.proto.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
